/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'LCDDEMO' 
 * Target:  'LCDDEMO_Debug' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "HC32F460JEUA.h"

/* LVGL::LVGL&LVGL9:Display&st7735@9.2.2 */
/* use display driver for st7735 */
#define LV_USE_ST7735	    1
/* LVGL::LVGL&LVGL9:Essential@9.2.2 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL


#endif /* RTE_COMPONENTS_H */
